2025-09-07 10:00:01 INFO Starting server on port 8000
2025-09-07 10:00:03 WARNING Cache miss for key=user:123
2025-09-07 10:00:05 ERROR Database connection failed: timeout after 5s
Traceback (most recent call last):
  File "/app/service.py", line 42, in connect
    client = db.connect(url)
  File "/app/db.py", line 10, in connect
    raise TimeoutError("timeout after 5s")
TimeoutError: timeout after 5s
2025-09-07 10:00:06 INFO Retrying connection (1/3)
2025-09-07 10:00:11 ERROR Migration failed: relation "users" does not exist
2025-09-07 10:00:12 INFO Shutting down
